# -*- coding: utf-8 -*-
"""MILESTONE 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uHlfgcnNtmdvjNpHyk9grPUjHt8N7_a0
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os



"""step 1:load data"""

df = pd.read_csv("retail_sales_dataset_2022_2024.csv")
df['date'] = pd.to_datetime(df['date'], errors='coerce')

print("Data Shape:", df.shape)
print(df.head())

"""# **CREATE OUTPUT** **FOLDER**"""

os.makedirs("eda_outputs", exist_ok=True)

"""step 2:data cleaning"""

# Convert sales to numeric
if 'sales' not in df.columns:
  df['sales']=df['units_sold']*df['price']
df['sales'] = pd.to_numeric(df['sales'], errors='coerce')

# Fill missing sales with median
df['sales'] = df['sales'].fillna(df['sales'].median())

# Drop duplicates
df = df.drop_duplicates()

# Remove invalid values (negative sales)
df = df[df['sales'] >= 0]

# Check missing values
print("Missing values (%):")
print(df.isnull().mean() * 100)

"""step 3:Exploratory Data Analysis"""

# Monthly trend
monthly = df.groupby(pd.Grouper(key='date', freq='ME'))['sales'].sum()
monthly.plot(kind='line', marker='o', figsize=(10,5), title="Monthly Sales Trend")
plt.xlabel("Month"); plt.ylabel("Sales"); plt.tight_layout()
plt.savefig("eda_outputs/monthly_sales_trend.png"); plt.show()

# Outlier detection
plt.figure(figsize=(6,4))
sns.boxplot(x=df['sales'])
plt.title("Outlier Detection in Sales")
plt.tight_layout(); plt.savefig("eda_outputs/sales_boxplot.png"); plt.show()

# Seasonality: Year vs Month heatmap
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
seasonality = df.groupby(['year','month'])['sales'].sum().unstack(0)
sns.heatmap(seasonality, cmap="YlGnBu", annot=True, fmt=".0f")
plt.title("Seasonality Heatmap (Year vs Month)")
plt.tight_layout(); plt.savefig("eda_outputs/seasonality_heatmap.png"); plt.show()

# Product-level trends (Top 5 products)
top_products = df.groupby('product_id')['sales'].sum().sort_values(ascending=False).head(5).index
for pid in top_products:
    temp = df[df['product_id']==pid]
    plt.figure(figsize=(10,4))
    plt.plot(temp['date'], temp['sales'])
    plt.title(f"Sales Trend - {pid}")
    plt.tight_layout()
    plt.savefig(f"eda_outputs/trend_{pid}.png"); plt.show()

# ---- Yearly Sales Summary ----
if 'year' not in df.columns:
    df['year'] = df['date'].dt.year

yearly_sales = df.groupby('year')['sales'].sum().sort_values(ascending=False)
yearly_sales.to_csv("yearly_sales_summary.csv")

plt.figure(figsize=(8,5))
sns.barplot(x=yearly_sales.index, y=yearly_sales.values,hue=yearly_sales.index, palette="magma",legend=False)
plt.title("Yearly Sales Summary")
plt.xlabel("Year")
plt.ylabel("Total Sales")
plt.tight_layout()
plt.savefig("yearly_sales_summary.png")
plt.show()
print("✅ Yearly Sales Summary chart saved as yearly_sales_summary.png")
print(yearly_sales)

"""step 4:Feature Engineering"""

df['quarter'] = df['date'].dt.to_period("Q").astype(str)
df['dayofweek'] = df['date'].dt.dayofweek
df['weekofyear'] = df['date'].dt.isocalendar().week

# Holiday indicator (Nov & Dec)
df['is_holiday_season'] = df['date'].dt.month.isin([11,12]).astype(int)

# Promotion flag (Yes/No → 1/0)
if 'promotion' in df.columns:
    df['promotion_flag'] = df['promotion'].astype(str).str.lower().map({'yes':1,'no':0}).fillna(0)
else:
    df['promotion_flag'] = 0

# Lag features (per product)
df = df.sort_values(['product_id','date'])
df['lag_1'] = df.groupby('product_id')['sales'].shift(1)
df['rolling_mean_7'] = df.groupby('product_id')['sales'].transform(lambda x: x.rolling(7, min_periods=1).mean())
df['rolling_mean_30'] = df.groupby('product_id')['sales'].transform(lambda x: x.rolling(30, min_periods=1).mean())

# Growth rate
df['growth_rate'] = df.groupby('product_id')['sales'].pct_change().fillna(0)

# Select key columns for cleaned dataset
columns_to_keep = [
    'date', 'product_id'
]

# Include product_name if available
if 'product_name' in df.columns:
    columns_to_keep.append('product_name')

columns_to_keep += [
    'units_sold', 'price', 'sales', 'year', 'month', 'quarter',
    'dayofweek', 'weekofyear', 'is_holiday_season', 'promotion_flag',
    'lag_1', 'rolling_mean_7', 'rolling_mean_30', 'growth_rate'
]

"""step 5:save processed file

"""

df.to_csv("cleaned_sales_data.csv", index=False)